# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Piko < Formula
  desc "PIKOlang (Private Innocent Kotlin Object) interpreter written in Go."
  homepage "https://github.com/matronator/piko"
  version "1.0.0"
  license "GPL-3.0-only"

  depends_on "git"
  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/matronator/piko/releases/download/v1.0.0/piko_Darwin_x86_64.tar.gz"
      sha256 "340a4dc36c772d570172b0edbf79423c3503ab843d62bc9f306e86a0aa56bed4"

      def install
        bin.install "piko"
      end
    end
    on_arm do
      url "https://github.com/matronator/piko/releases/download/v1.0.0/piko_Darwin_arm64.tar.gz"
      sha256 "45d0ae23d92619841c395d0b1c02b49eb4208bf530ceb18c7b9907f7be23d07f"

      def install
        bin.install "piko"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matronator/piko/releases/download/v1.0.0/piko_Linux_x86_64.tar.gz"
        sha256 "5760ca1d3ee055506768b88fad57a52675a17c7b6b2915681e55b83e2300d024"

        def install
          bin.install "piko"
        end
      end
    end
  end
end
